default_stages:
    - pre-commit
    - pre-push
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-json
    -   id: check-ast
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, staging, --branch, production]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.14
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        exclude: docs\*
        stages:
          - manual
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: 'v1.10.0'
    hooks:
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: '0.36.1'
    hooks:
    -   id: check-readthedocs
-   repo: https://github.com/adamchainz/blacken-docs
    rev: "1.20.0"
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black
